FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir pandas numpy evidently

COPY monitoring/ ./monitoring/
COPY logs/ ./logs/
COPY reports/ ./reports/

CMD ["python", "-m", "monitoring.data_drift"]
